#pragma config(Sensor, in1,    armPot,         sensorPotentiometer)
#pragma config(Sensor, in2,    LineLeft,       sensorLineFollower)
#pragma config(Sensor, in3,    LineMid,        sensorLineFollower)
#pragma config(Sensor, in4,    LineRight,      sensorLineFollower)
#pragma config(Sensor, dgtl1,  rightEncoder,   sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,    sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  frontStop,      sensorTouch)
#pragma config(Sensor, dgtl7,  sonarSensor,    sensorSONAR_cm)
#pragma config(Motor,  port2,           rightMotor,    tmotorServoContinuousRotation, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorServoContinuousRotation, openLoop)
#pragma config(Motor,  port5,           armMotor,      tmotorServoContinuousRotation, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
void autonomous()
{
	ClearTimer(T1);
	int normalspeed;
	int slowspeed;
	normalspeed = 80;
	slowspeed = 65;
	SensorValue[rightEncoder] = 0;
	SensorValue[leftEncoder] = 0;

	while (time1[T1] < 30000) //i.e. 30 seconds in milliseconds
	{
		//ENTER ALL AUTONOMOUS CODE BETWEEN HERE AND THE END AUTONOMOUS LINE BELOW

		//move forward (replace chunk of code if using line followers)
		while(SensorValue[sonarSensor] > 5 )//move forward until 5cm from pipe
		{
			if(SensorValue[leftEncoder] == SensorValue[rightEncoder])
			{
				motor[rightMotor] = normalspeed;
				motor[leftMotor] = normalspeed;
			}

			if(SensorValue[rightEncoder] < SensorValue[leftEncoder])
			{
				motor[rightMotor] = normalspeed;
				motor[leftMotor] = slowspeed;
			}

			if(SensorValue[leftEncoder] < SensorValue[rightEncoder])
			{
				motor[rightMotor] = slowspeed;
				motor[leftMotor] = normalspeed;
			}
		}


	//Shut off both motors
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;

	//needs additional code to drop balls & score


	//END AUTONOMOUS
	}
}

//when under remote control
void teleop()
{
	ClearTimer(T1);

	while(time1[T1] < 180000)  //2.5 min
	{
		// ENTER ALL DRIVER OPERATED CODE BETWEEN HERE AND THE END DRIVER CONTROL LINE BELOW//
		motor[leftMotor] = vexRT[Ch3];
		motor[rightMotor] = vexRT[Ch2];

		if (vexRT[btn6U] == 1)
		{
			//insert whatever you want btn6U to do
		}

		if (vexRT[btn6D] == 1)
		{
			//insert whatever you want btn6D to do
		}
	}
	//END DRIVER OPERATED CONTROL

	//shut off both motors
	motor[leftMotor] = 0;
	motor[rightMotor] = 0;
}


task main()
{
	while(vexRT[Btn6U]==0)
	{
		wait1Msec(1); //do nothing until user presses button to start autonomous
	}

	autonomous();

	//do nothing until user presses button to start teleop
	while  (vexRT[Btn6U]==0)
	{
		wait1Msec(1);
	}

	teleop();	//under driver control
}
